---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testing-app-dev
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
  labels:
    rhdh-demo/application: testing-app
spec:
  project: default
  source:
    repoURL: https://github.com/rhdh-dev-demo/testing-app-gitops.git
    targetRevision: HEAD
    path: ./helm/app
    helm:
      valueFiles:
        - Values.yaml
      # values: |
      #   # Override namespace for dev
      #   app:
      #     namespace: testing-app-dev
      #   image:
      #     tag: latest
      #   # Add dev-specific overrides here
  destination:
    server: https://kubernetes.default.svc
    namespace: testing-app-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true
    retry:
      limit: -1
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 2m